### ISSUE TITLE
DM Support

### ISSUE THREAD

**Issue by Chew** [Chew/DIRCord#1]
it's a given, really.

**Comment by Chewsterchew** [comment]
My plan this is to make a category called "Messages" that contains messages from users. 
Any "channels" in this category will be treated as messages to a user, instead of messages to a channel.
Any messages received from a user will be handled by creating a channel in this category (or creating it if it doesn't exist) and putting the channel. The user will be mentioned via client ID, then the message will probably be embedded to avoid confusion. 

This will allow messages with ChanServ and NickServ, however each message will be sent to discord, but these bois usually send 10s of messages, so I'll try to combine messages within a certain time and send them as one embed.

**Comment by Chew** [comment]
DM support is here, more bugs will be opened to fix bugs found with it
